import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/sharedComponents/footer";
import Navbar from "@/sharedComponents/header";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "COCAnuaObio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="bg-white z-[400px]"
          style={{
            boxShadow:
              "0 4px 6px -1px rgba(251, 191, 36, 0.1), 0 2px 4px -1px rgba(251, 191, 36, 0.06)",
          }}
        >
          
          <div className=" justify-between mx-8 flex  font-bold text-[#174124] flex-row   items-center">
          <div className=" ">
            <Image
              src="/images/coclogo2.png"
              alt="churchLogo"
              width={80}
              height={80}
            />
          </div>
            
            <Link
              href="/"
              className="relative inline-block pb-1 transition-all duration-200 
              before:absolute before:bottom-0 before:left-0 before:w-full 
              before:h-[4px] before:bg-[#f3bb44] before:scale-x-0 
              before:origin-left before:transition-transform before:duration-200 
              hover:before:scale-x-100"
            >
              Home
            </Link>

            <Link
              href="/sermon"
              className="relative inline-block pb-1 transition-all duration-200 
              before:absolute before:bottom-0 before:left-0 before:w-full 
              before:h-[4px] before:bg-[#f3bb44] before:scale-x-0 
              before:origin-left before:transition-transform before:duration-200 
              hover:before:scale-x-100"
            >
              Sermon
            </Link>
            <Link
              href="/teaching"
              className="relative inline-block pb-1 transition-all duration-200 
              before:absolute before:bottom-0 before:left-0 before:w-full 
              before:h-[4px] before:bg-[#f3bb44] before:scale-x-0 
              before:origin-left before:transition-transform before:duration-200 
              hover:before:scale-x-100"
            >
              Teachings
            </Link>
            <Link
              href="/gallery"
              className="relative inline-block pb-1 transition-all duration-200 
              before:absolute before:bottom-0 before:left-0 before:w-full 
              before:h-[4px] before:bg-[#f3bb44] before:scale-x-0 
              before:origin-left before:transition-transform before:duration-200 
              hover:before:scale-x-100"
            >
              Gallery
            </Link>
          </div>
        </div>

        <main className="bg-[#fff]">{children}</main>
        <div className="bg-black">
          <Footer />
        </div>
      </body>
    </html>
  );
}
